version: '3.1'

services:

  db:
    image: yantao0527/ai_mysql:0.0.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  agents:
    image: yantao0527/ai_agents:0.0.1
    restart: always
    ports:
      - 8081:8501
    volumes:
      - ./.env.stack:/app/.env
    env_file:
      - ./.env.stack
    depends_on:
      - db
    